# CI for ros_comm on Mac.
# Based on: http://wiki.ros.org/kinetic/Installation/OSX/Homebrew/Source

os: osx
osx_image: xcode9.2
language:
  - generic

before_install:
  - brew update
  - brew tap ros/deps
  - mkdir -p ~/Library/Python/2.7/lib/python/site-packages
  - echo "$(brew --prefix)/lib/python2.7/site-packages" >> ~/Library/Python/2.7/lib/python/site-packages/homebrew.pth
  - brew install python
  - sudo -H python2 -m pip install -U pip
  - sudo -H python2 -m pip install wxPython

install:
  - echo "install"

before_script:
  - echo "before_script"

script:
  - echo "script"

