# CI for ros_comm on Mac.
# Based on: http://wiki.ros.org/kinetic/Installation/OSX/Homebrew/Source

os: osx
osx_image: xcode9.2
language:
  - generic

before_install:
  - brew update
  - brew tap ros/deps

install:
  - echo "install"

before_script:
  - echo "before_script"

script:
  - echo "script"

