# CI for ros_comm on Mac.
# Based on: http://wiki.ros.org/kinetic/Installation/OSX/Homebrew/Source

os: osx
osx_image: xcode9.2
language:
  - generic

env:
  global:
    - CATKIN_WS=~/ros_catkin_ws

before_install:
  - brew update
  - brew tap ros/deps
  - sudo -H python2 -m pip install -U wxPython wstool rosdep rosinstall rosinstall_generator rospkg catkin-pkg sphinx
  - sudo -H rosdep init
  - rosdep update

install:
  - mkdir $CATKIN_WS
  - cd $CATKIN_WS
  - rosinstall_generator ros_comm --rosdistro kinetic --deps --wet-only --tar > kinetic-ros_comm-wet.rosinstall
  - wstool init -j8 src kinetic-ros_comm-wet.rosinstall
  - rosdep install --from-paths src --ignore-src --rosdistro kinetic -y --skip-keys google-mock
  - ls -la .

before_script:
  - echo "before_script"

script:
  - echo "script"

